package curso.api.rest.service;

import java.util.Properties;

import javax.mail.Address;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import org.springframework.stereotype.Service;

@Service
public class ServiceEnviaEmail {
	private String userName ="reinaldo.mendes@sapo.pt";
	private String senha = "Rcmereinas1";

	public void enviarEmail(String assunto, String emailDestino, String mensagem) throws Exception {
		
		/*Properties properties = new Properties();
		properties.put("mail.smtp.ssl.trust", "*");
		properties.put("mail.smtp.auth", true);
		properties.put("mail.smtp.starttls", true);
		properties.put("mail.smtp.host", "smtp.sapo.pt");
		properties.put("mail.smtp.port","465");
		properties.put("mail.smtp.socketFactory.port","465");
		properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");*/
		/* String host = "smtp.sapo.pt";
		 Properties  properties = new Properties();
		 properties.put("mail.smtp.host", host);
		 properties.put("mail.smtp.port", "465");
		 properties.put("mail.smtp.ssl.enable", "true");
		 properties.put("mail.smtp.auth", "true");
		Session session = Session.getInstance(properties, new Authenticator() {
			@Override
			protected PasswordAuthentication getPasswordAuthentication() {
				
				return new PasswordAuthentication(userName, senha);
			}
		});
		Address[] toUser = InternetAddress.parse(emailDestino);
*/
		/* Message message = new MimeMessage(session);
		message.setFrom(new InternetAddress(userName));
		message.setRecipients(Message.RecipientType.TO, toUser);
		message.setSubject(assunto);
		message.setText(mensagem);

		Transport.send(message);*/
		
		
		// Put recipient’s address
		 // Put sender’s address
		 String from = "reinaldo.mendes@sapo.pt";
		 final String username = "reinaldo.mendes@sapo.pt";//username generated by Pepipost
		 final String password = "Rcmreinas1";//password generated by Pepipost
		 // Paste host address from the SMTP relay tab in Integrations from your Pepipost App
		 String host = "smtp.sapo.pt";
		 Properties  properties = new Properties();
		 properties.put("mail.smtp.host", host);
		 properties.put("mail.smtp.port", "465");
		 properties.put("mail.smtp.ssl.enable", "true");
		 properties.put("mail.smtp.auth", "true");
		 // Get the Session object.
		 Session session = Session.getInstance( properties,
		 new javax.mail.Authenticator() {
		 protected PasswordAuthentication getPasswordAuthentication() {
		 return new PasswordAuthentication(username, password);
		 }
		 });
		 session.setDebug(true);
		 try {
		 // Create a default MimeMessage object.
		 Message message = new MimeMessage(session);
		 // Set From: header field
		 message.setFrom(new InternetAddress(from));
		 // Set To: header field
		 message.setRecipients(Message.RecipientType.TO,
		 InternetAddress.parse(emailDestino));
		 // Set Subject: header field
		 message.setSubject(assunto);
		 // Put the content of your message
		 message.setText(mensagem);
		 // Send message
		 System.out.println("Sending msg");
		 Transport.send(message);
		 System.out.println("Sent message successfully....");
		 } catch (MessagingException e) {
		 throw new RuntimeException(e);
		 }
		 }
	}

